### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by Kenix3** [Kenix3/libultraship#62]
In order to affirm the project license after moving this project from https://github.com/HarbourMasters/Shipwright to the repository at https://github.com/kenix3/libultraship, we need to ask everyone to affirm the [license in the repository](https://github.com/Kenix3/libultraship/blob/main/LICENSE).

Please comment affirming you agree, and are able, to having your prior contributions licensed under the terms described the [license in this repository](https://github.com/Kenix3/libultraship/blob/main/LICENSE).

We're largely asking this because the move constituted leaving the subrepo. The GitHub ToS is not _perfectly_ clear how licenses apply to subrepos, so to be safe we are asking for an affirmation. Beyond that, we also changed the copyright line in the license file as "Harbour Masters" does not currently exist as a legal entity. Thankyou.

@Kenix3 @NEstelami @KiritoDv  @dcvz @louist103 @Emill @briaguya-ai @leggettc18 @Rozelette @garrettjoecox @GaryOderNichts @Sirius902 @aMannus @Baoulettes @lilDavid @MelonSpeedruns @jbodner09 @PurpleHato @GreatArgorath @qurious-pixel @vaguerant @earthcrafterman @Random06457 @AloXado320 @th-2021 @JoshDuMan @Alto1772 @Archez @Sarge-117 @crowell @sholdee @m4xw @JakeEdvenson @Nycz-lab @InfoManiac742 @guaycuru @modestposer @Stormghetti @Dog @ChristopherJTrent @agamache @TheLegendOfLame @andrewwvc @ProjectRevoTPP @sparklingshampoo @MaikelChan @kev4cards

**Comment by Kenix3** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by InfoManiac742** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by crowell** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by GreatArgorath** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Sarge-117** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by agamache** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by KiritoDv** [comment]
I affirm that my contributions will be licensed under the terms in the
license in this repository.

**Comment by briaguya0** [comment]
yes

**Comment by RevoSucks** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by JoshDuMan** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by 1SDANi** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by modestposer** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Archez** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by garrettjoecox** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Sirius902** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by qurious-pixel** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Emill** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by ghost** [comment]
I affirm my consent to have my contributions licensed under the new LibUltraship repository.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kenix3 ***@***.***>
Sent: Tuesday, December 6, 2022 4:56:05 PM
To: Kenix3/libultraship ***@***.***>
Cc: ChristopherJTrent ***@***.***>; Mention ***@***.***>
Subject: [Kenix3/libultraship] Project License (Issue #62)


In order to affirm the project license after moving this project from https://github.com/HarbourMasters/Shipwright to the repository at https://github.com/kenix3/libultraship, we need to ask everyone to affirm the license in the repository<https://github.com/Kenix3/libultraship/blob/main/LICENSE>.

Please comment affirming you agree to having your prior contributions licensed under the terms described the license in this repository<https://github.com/Kenix3/libultraship/blob/main/LICENSE>.

@Kenix3<https://github.com/Kenix3> @NEstelami<https://github.com/NEstelami> @KiritoDv<https://github.com/KiritoDv> @dcvz<https://github.com/dcvz> @louist103<https://github.com/louist103> @Emill<https://github.com/Emill> @briaguya-ai<https://github.com/briaguya-ai> @leggettc18<https://github.com/leggettc18> @Rozelette<https://github.com/Rozelette> @garrettjoecox<https://github.com/garrettjoecox> @GaryOderNichts<https://github.com/GaryOderNichts> @Sirius902<https://github.com/Sirius902> @aMannus<https://github.com/aMannus> @Baoulettes<https://github.com/Baoulettes> @lilDavid<https://github.com/lilDavid> @MelonSpeedruns<https://github.com/MelonSpeedruns> @jbodner09<https://github.com/jbodner09> @PurpleHato<https://github.com/PurpleHato> @GreatArgorath<https://github.com/GreatArgorath> @qurious-pixel<https://github.com/qurious-pixel> @vaguerant<https://github.com/vaguerant> @earthcrafterman<https://github.com/earthcrafterman> @Random06457<https://github.com/Random06457> @AloXado320<https://github.com/AloXado320> @th-2021<https://github.com/th-2021> @JoshDuMan<https://github.com/JoshDuMan> @Alto1772<https://github.com/Alto1772> @Archez<https://github.com/Archez> @Sarge-117<https://github.com/Sarge-117> @crowell<https://github.com/crowell> @sholdee<https://github.com/sholdee> @m4xw<https://github.com/m4xw> @JakeEdvenson<https://github.com/JakeEdvenson> @Nycz-lab<https://github.com/Nycz-lab> @InfoManiac742<https://github.com/InfoManiac742> @guaycuru<https://github.com/guaycuru> @modestposer<https://github.com/modestposer> @Stormghetti<https://github.com/Stormghetti> @Dog<https://github.com/Dog> @ChristopherJTrent<https://github.com/ChristopherJTrent> @agamache<https://github.com/agamache> @TheLegendOfLame<https://github.com/TheLegendOfLame> @andrewwvc<https://github.com/andrewwvc> @ProjectRevoTPP<https://github.com/ProjectRevoTPP> @sparklingshampoo<https://github.com/sparklingshampoo> @MaikelChan<https://github.com/MaikelChan> @kev4cards<https://github.com/kev4cards>

**Comment by Dumbledork01** [comment]
I affirm my consent to have my contributions licensed under the new
LibUltraship repository.

**Comment by louist103** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by leggettc18** [comment]
I affirm that my contributes will be licensed under the terms in the license in this repository.

**Comment by MaikelChan** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by sholdee** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Alto1772** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by th-2021** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by PurpleHato** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by jbodner09** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by aMannus** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Random06457** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by GaryOderNichts** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by guaycuru** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by vaguerant** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by NEstelami** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by dcvz** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by MelonSpeedruns** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Baoulettes** [comment]
I affirm that all my contributions there will be licensed under the terms in the license of this repository

**Comment by lilDavid** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Stormghetti** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by AloXado320** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Kenix3** [comment]
@Rozelette @Nycz-lab @Dog @TheLegendOfLame @andrewwvc @sparklingshampoo @kev4cards 
Still waiting on response from you guys! Are there any questions or concerns that we can discuss?

**Comment by Rozelette** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Nycz-lab** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by kev4cards** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by TheLegendOfLame** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by andrewwvc** [comment]
I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Kenix3** [comment]
@sparklingshampoo This will be your final ping on the matter. If the new license can not be affirmed then I will have to remove the contribution. Thankyou!

**Comment by sparklingshampoo** [comment]
Sorry about the very late response, this is a second account for legal reasons.

I affirm that my contributions will be licensed under the terms in the license in this repository.

**Comment by Kenix3** [comment]
We now have 100% agreement. The license is affirmed.
